language: java
sudo: false
jdk:
  - oraclejdk8

services:
  - docker

# setup the paradoxical deployment model using:
#   git submodule add -b master https://github.com/paradoxical-io/deployment-docker.git .deployment
git:
  submodules: false
before_install:
  # https://git-scm.com/docs/git-submodule#_options:
  # --remote
  # Instead of using the superproject’s recorded SHA-1 to update the submodule,
  # use the status of the submodule’s remote-tracking (branch.<name>.remote) branch (submodule.<name>.branch).
  # --recursive
  # https://github.com/travis-ci/travis-ci/issues/4099
  - git submodule update --init --remote --recursive
after_success:
  - ./.deployment/deploy.sh